/* THIS FILE IS AUTO-GENERATED BY PAYLOAD. DO NOT MODIFY IT. */
/* Run `pnpm payload:generate` to regenerate types */
/* eslint-disable @typescript-eslint/no-empty-object-type */

export interface Config {
  collections: {
    users: User
    media: Media
    categories: Category
    posts: Post
  }
  globals: {}
}

export interface User {
  id: string
  email: string
  role: 'user' | 'admin'
  name?: string | null
  avatar?: string | Media | null
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  caption?: string | null
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  createdAt: string
  updatedAt: string
}

export interface Category {
  id: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  createdAt: string
  updatedAt: string
}

export interface Post {
  id: string
  title: string
  slug: string
  excerpt?: string | null
  content: unknown // Lexical rich text
  featuredImage?: string | Media | null
  categories?: (string | Category)[] | null
  author: string | User
  status: 'draft' | 'published' | 'archived'
  publishedAt?: string | null
  createdAt: string
  updatedAt: string
}
